- win_environment:
      level: user
      name: '{{ item.name }}'
      value: '{{ item.value }}'
  with_items:
    - name: SCOOP
      value: '{{ scoop_dir }}'
    - name: JAVA_HOME
      value: '{{ scoop_dir }}/apps/{{ java_package }}/current'

- win_path:
    scope: user
    elements:
      - '%JAVA_HOME%\bin'

- name: Scoopのインストール
  win_shell: |
      Set-StrictMode -Off
      Invoke-Expression (New-Object Net.Webclient).DownloadString('https://get.scoop.sh')
  args:
    creates: '{{ scoop_dir }}'

- name: Gitのインストール
  win_shell: scoop install git
  args:
    creates: '{{ scoop_dir }}\apps\git'

- name: Scoopにバケットを登録
  win_shell: scoop bucket add {{ item }}
  args:
    creates: '{{ scoop_dir }}\buckets\{{ item }}'
  with_items:
    - extras
    - java

- win_shell: scoop install {{ item }}
  args:
    creates: '{{ scoop_dir }}\apps\{{ item }}'
  with_items:
    - googlechrome
    - vscode-portable
    - '{{ java_package }}'
    - graphviz

- name: Powershellのヘルプを更新する
  win_shell: Update-Help -Force -UICulture {{ item }} -ErrorAction Continue
  with_items:
    - ja-JP
    - en-US
  failed_when: false
