- name: ダークテーマにする
  win_regedit:
    path: HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize
    name: AppsUseLightTheme
    data: 0
    type: dword

- name: Visual Studio Codeの設定
  win_copy:
    dest: '{{ vscode_data_dir }}/user-data/User/settings.json'
    src: vscode-settings.json

- name: Powershellの設定フォルダを作成する
  win_file: state=directory path={{ home_dir }}/{{ item }}
  with_items:
    - Documents/WindowsPowerShell

- name: PowerShellのprofile.ps1を設定する
  win_copy:
    dest: '{{ home_dir }}/Documents/WindowsPowerShell/profile.ps1'
    src: profile.ps1
