- name: ダークテーマにする
  win_regedit:
    path: HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize
    name: AppsUseLightTheme
    data: 0
    type: dword

- name: エクスプローラの設定を変更する
  win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
    name: '{{ item.name }}'
    data: '{{ item.data }}'
    type: dword
  with_items:
    - name: ShowTaskViewButton
      data: 0
    - name: NavPaneExpandToCurrentFolder
      data: 1
    - name: HideFileExt
      data: 0
    - name: Hidden
      data: 1
    # 空のドライブも表示させる
    - name: HideDrivesWithNoMedia
      data: 0
    # 保護されたオペレーティングシステムファイルも表示させる
    - name: ShowSuperHidden
      data: 1
    # コントロールパネル等も表示させる
    - name: NavPaneShowAllFolders
      data: 1
    # チェックボックスを表示させる
    - name: AutoCheckSelect
      data: 1
    # 初期表示フォルダをPCにする
    - name: LaunchTo
      data: 1

# - name: タスクバーからPeopleを消す
#   win_regedit:
#     path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced\People
#     name: PeopleBand
#     data: 0
#     type: dword

- name: .sshフォルダを作成する
  win_file: path={{ home_dir }}/.ssh state=directory

- name: SSHキーをコピーする
  win_copy:
    dest: '{{ home_dir }}/.ssh/{{ item }}'
    src: '{{ secret_dir }}/{{ item }}'
  with_items:
    - id_rsa
    - id_rsa.pub

- name: Gitの設定を行う
  win_copy:
    dest: '{{ home_dir }}/.gitconfig'
    src: .gitconfig

- name: Visual Studio Code拡張のインストール状況を確認する
  win_find:
    paths: '{{ vscode_data_dir }}/extensions'
    patterns: '{{ item }}-*'
    file_type: directory
  with_items: '{{ vscode_extensions }}'
  changed_when: false
  register: vscodeExt

- name: Visual Studio Code拡張をインストールする
  win_shell: code --install-extension {{ item.item }}
  when: 0 == item.matched
  with_items: '{{ vscodeExt.results }}'

- name: Powershellの設定フォルダを作成する
  win_file: state=directory path={{ home_dir }}/{{ item }}
  with_items:
    - Documents/WindowsPowerShell

- name: PowerShellのprofile.ps1を設定する
  win_copy:
    dest: '{{ home_dir }}/Documents/WindowsPowerShell/profile.ps1'
    src: profile.ps1
