- aur: name={{ item }} skip_installed=yes
  become: no
  #
  with_items:
    - visual-studio-code-bin
    - powershell-bin

- name: Yarnのインストール
  package: name=yarn
  #
  #

- name: PHP開発ツールのインストール
  package: name={{ item }}
  #
  #
  with_items:
    - composer
    - php-pgsql
    - xdebug

- name: phpのPDO拡張(PostgreSQL)を有効にする
  lineinfile:
    path: /etc/php/php.ini
    regexp: ^;?extension=pdo_pgsql
    line: extension=pdo_pgsql

#
- name: Python開発ツールのインストール
  package: name={{ item }}
  with_items:
    - python-pipenv
    - python-pylint
    - autopep8

- name: C#開発ツールのインストール
  package: name={{ item }}
  with_items:
    - mono
    - dotonet-sdk
    - dotonet-host

- name: msbuildのインストール
  aur: name=msbuild-stable skip_installed=yes
  become: no
