- name: Cocos2d-xのダウンロード
  become: no
  get_url:
    dest: '{{ home_dir }}/Downloads/cocos2d-x-{{ cocos2d_x_version }}.zip'
    url: http://digitalocean.cocos2d-x.org/Cocos2D-X/cocos2d-x-{{ cocos2d_x_version }}.zip

- name: Cocos2d-xのフォルダ作成
  become: no
  file: state=directory path={{ user_bin_dir }}/cocos2d-x

- name: Cocos2d-xを展開
  become: no
  unarchive:
    remote_src: yes
    dest: '{{ user_bin_dir }}/cocos2d-x'
    src: '{{ home_dir }}/Downloads/cocos2d-x-{{ cocos2d_x_version }}.zip'

- name: Cocos2d-x現行バージョンのシンボリックリンクを張る
  file:
    state: link
    path: '{{ user_bin_dir }}/cocos2d-x/current'
    src: '{{ user_bin_dir }}/cocos2d-x/cocos2d-x-{{ cocos2d_x_version }}'
