- win_shell: scoop install {{ item }}
  args:
    creates: '{{ scoop_dir }}\apps\{{ item }}'
  with_items:
    - vscode
    # - powershell-bin

- name: Powershellのヘルプを更新する
  win_shell: Update-Help -Force -UICulture {{ item }} -ErrorAction Continue
  # args:
  #   executable: /usr/bin/pwsh
  with_items:
    - ja-JP
    - en-US
  failed_when: false

- win_shell: scoop install {{ item }}
  args:
    creates: '{{ scoop_dir }}\apps\{{ item }}'
  with_items:
    - jq
    - nodejs-lts
    - yarn
    - python
    - dotnet-sdk
    # - dotnet-host
    - openjdk
    - graphviz
    - vagrant
    # - docker-compose

- name: PHP開発ツールのインストール
  win_shell: scoop install {{ item }}
  args:
    creates: '{{ scoop_dir }}\apps\{{ item }}'
  with_items:
    - composer
    # - php-pgsql
    - php-xdebug

# - name: phpのPDO拡張(PostgreSQL)を有効にする
#   lineinfile:
#     path: /etc/php/php.ini
#     regexp: ^;?extension=pdo_pgsql
#     line: extension=pdo_pgsql

# TODO pip で入れるのが妥当か？
# - name: Python開発ツールのインストール
#   package: name={{ item }}
#   with_items:
#     - python-pipenv
#     - python-pylint
#     - autopep8
