- name: 不要なストアアプリのインストール状況を確認
  win_shell: Get-AppxPackage -Name {{ item }} | ForEach-Object { Write-Host $_.PackageFullName }
  with_items:
    # ないと困るかもしれないもの
    - Microsoft.ZuneVideo # 映画 & テレビ
    - Microsoft.ZuneMusic # Grooveミュージック
    # Web上で代替可
    - Microsoft.WindowsCalculator # 電卓
    - Microsoft.MicrosoftOfficeHub
    - Microsoft.SkypeApp
    - Microsoft.MicrosoftStickyNotes # 付箋
    # なくても良さそうなもの
    - Microsoft.MicrosoftSolitaireCollection
    - Microsoft.WindowsSoundRecorder
    - Microsoft.MixedReality.Portal
    - Microsoft.Microsoft3DViewer
    - Microsoft.Getstarted # ヒント
    - Microsoft.WindowsFeedbackHub
    # 明らかに不要なもの
    - Microsoft.MSPaint # ペイント3D
    - microsoft.windowscommunicationsapps # メールとカレンダー
    - Microsoft.XboxApp # Xbox 本体コンパニオン
    - Microsoft.OneConnect # モバイル通信プラン
  changed_when: false
  register: winStoreApp

- name: 不要なストアアプリのアンインストール
  win_shell: Remove-AppxPackage {{ item.stdout }}
  when: item.stdout != ''
  with_items: '{{ winStoreApp.results }}'
