- name: Gitの設定を行う
  copy:
    dest: '{{ home_dir }}/.gitconfig'
    src: .gitconfig

- name: Visual Studio Code拡張のインストール状況を確認する
  find:
    paths: '{{ home_dir }}/.vscode/extensions'
    patterns: '{{ item }}-*'
    file_type: directory
  with_items: '{{ vscode_extensions }}'
  changed_when: false
  register: vscodeExt

- name: Visual Studio Code拡張をインストールする
  shell: code --install-extension {{ item.item }}
  when: 0 == item.matched
  with_items: '{{ vscodeExt.results }}'

- name: Visual Studio Codeの設定を行う
  copy:
    dest: '{{ home_dir }}/Library/Application Support/Code/User/{{ item }}'
    src: vscode-{{ item }}
  with_items:
    - locale.json
    - settings.json

- name: Powershellの設定フォルダを作成する
  file: state=directory path={{ home_dir }}/{{ item }}
  with_items:
    - .config
    - .config/powershell

- name: PowerShellのprofile.ps1を設定する
  template:
    dest: '{{ home_dir }}/.config/powershell/profile.ps1'
    src: profile.j2.ps1
