- name: Gitの設定を行う
  copy:
    dest: '{{ home_dir }}/.gitconfig'
    src: .gitconfig

- name: Visual Studio Code拡張のインストール状況を確認する
  find:
    paths: '{{ home_dir }}/.vscode/extensions'
    patterns: '{{ item }}-*'
    file_type: directory
  with_items: '{{ vscode_extensions }}'
  changed_when: false
  register: vscodeExt

- name: Visual Studio Code拡張をインストールする
  shell: code --install-extension {{ item.item }}
  when: 0 == item.matched
  with_items: '{{ vscodeExt.results }}'

- name: Visual Studio Codeの設定を行う
  copy:
    dest: '{{ vscode_config_dir[env_alias] }}/{{ item }}'
    src: vscode-{{ item }}
  with_items:
    - locale.json
    - settings.json

- name: Powershellの設定フォルダを作成する
  file: state=directory path={{ home_dir }}/{{ item }}
  with_items:
    - .config
    - .config/powershell

- name: PowerShellのprofile.ps1を設定する
  template:
    dest: '{{ home_dir }}/.config/powershell/profile.ps1'
    src: profile.j2.ps1

- name: Yarnのバイナリ配置先を取得する
  shell: yarn global bin
  register: yarn_bin
  changed_when: false

# 180916: Ansible 2.6.3 on Mac だとなぜか yarn モジュールがこけるので仕方なくシェルを叩く
- shell: yarn global add {{ item.pkg }}
  args:
    creates: '{{ yarn_bin.stdout }}/{{ item.bin }}'
  with_items:
    - pkg: cordova
      bin: cordova
    - pkg: vue-cli
      bin: vue
