- name: Gitの設定を行う
  win_copy:
    dest: '{{ home_dir }}/.gitconfig'
    src: .gitconfig

- name: Visual Studio Code拡張のインストール状況を確認する
  win_find:
    paths: '{{ home_dir }}/.vscode/extensions'
    patterns: '{{ item }}-*'
    file_type: directory
  with_items: '{{ vscode_extensions }}'
  changed_when: false
  register: vscodeExt

- name: Visual Studio Code拡張をインストールする
  win_shell: code --install-extension {{ item.item }}
  when: 0 == item.matched
  with_items: '{{ vscodeExt.results }}'

- name: Visual Studio Codeの設定を行う
  win_copy:
    dest: '{{ vscode_config_dir[env_alias] }}/{{ item }}'
    src: vscode-{{ item }}
  with_items:
    - locale.json
    - settings.json

- name: Powershellの設定フォルダを作成する
  win_file: state=directory path={{ home_dir }}/{{ item }}
  with_items:
    # - Documents
    - Documents/WindowsPowerShell

- name: PowerShellのprofile.ps1を設定する
  win_template:
    dest: '{{ home_dir }}/Documents/WindowsPowerShell/profile.ps1'
    src: profile.j2.ps1

- name: Yarnのバイナリ配置先を取得する
  shell: '{{ scoop_dir }}/shims/yarn.exe global bin'
  register: yarn_bin
  changed_when: false

#
- shell: '{{ scoop_dir }}/shims/yarn.exe global bin {{ item.pkg }}'
  args:
    creates: '{{ yarn_bin.stdout }}/{{ item.bin }}'
  with_items:
    - pkg: cordova
      bin: cordova
    - pkg: vue-cli
      bin: vue
