- name: Gitの設定を行う
  win_copy:
    dest: '{{ home_dir }}/.gitconfig'
    src: .gitconfig

- name: Visual Studio Code拡張のインストール状況を確認する
  win_find:
    paths: '{{ home_dir }}/.vscode/extensions'
    patterns: '{{ item }}-*'
    file_type: directory
  with_items: '{{ vscode_extensions }}'
  changed_when: false
  register: vscodeExt

- name: Visual Studio Code拡張をインストールする
  win_shell: code --install-extension {{ item.item }}
  when: 0 == item.matched
  with_items: '{{ vscodeExt.results }}'

- name: Visual Studio Codeの設定を行う
  win_copy:
    dest: '{{ home_dir }}/AppData/Roaming/Code/User/{{ item }}'
    src: vscode-{{ item }}
  with_items:
    - locale.json
    - settings.json

- name: Powershellの設定フォルダを作成する
  win_file: state=directory path={{ home_dir }}/Documents/WindowsPowerShell

- name: PowerShellのprofile.ps1を設定する
  win_template:
    dest: '{{ home_dir }}/Documents/WindowsPowerShell/profile.ps1'
    src: profile.j2.ps1
