- hosts: local
  become: no
  connection: local

  tasks:
    - name: .xprofileがなければ作成する
      file: 'state=touch path={{ home_dir }}/.xprofile'
      changed_when: false

    - name: Mozcの設定を行う
      lineinfile:
        path: '{{ home_dir }}/.xprofile'
        line: '{{ item }}'
      with_items:
        - export GTK_IM_MODULE=fcitx
        - export QT_IM_MODULE=fcitx
        - export XMODIFIERS=@im=fcitx

    - name: IME切り替えキーを「全角/半角」のみにする
      lineinfile:
        path: '{{ home_dir }}/.config/fcitx/config'
        regexp: ^TriggerKey=
        line: TriggerKey=ZENKAKUHANKAKU

    - name: Gitの設定を行う
      copy:
        dest: '{{ home_dir }}/.gitconfig'
        src: files/.gitconfig

    - name: Visual Studio Code拡張をインストールする
      shell: 'code --install-extension {{ item }}'
      with_items:
        - ms-ceintl.vscode-language-pack-ja
        - editorconfig.editorconfig
        - esbenp.prettier-vscode
        - vscoss.vscode-ansible

    - name: Visual Studio Codeを日本語化する
      copy:
        dest: '{{ home_dir }}/.config/Code/User/locale.json'
        src: files/vscode-locale.json

    - name: Cajaの設定を行う
      dconf: 'key={{ item.key }} value={{ item.value }}'
      with_items:
        - key: /org/mate/caja/preferences/show-hidden-files
          value: 'true'
        - key: /org/mate/caja/preferences/default-folder-viewer
          value: "'list-view'"
