- hosts: all
  connection: winrm
  vars:
    ansible_ssh_port: 5985
    ansible_winrm_server_cert_validation: ignore

    home_dir: '{{ ansible_env.USERPROFILE }}'
    scoop_dir: C:\bin\scoop
    java_package: adoptopenjdk-lts-hotspot
    vscode_data_dir: '{{ scoop_dir }}/persist/vscode-portable/data'

  roles:
    - core
    - tools
    - pref

    - tools-update
    - tools-remove
